#-------------------------------------------------
#
# Project created by QtCreator 2018-03-07T22:53:45
#
#-------------------------------------------------

QT       += core gui

greaterThan(QT_MAJOR_VERSION, 4): QT += widgets

TARGET = graphics
TEMPLATE = app
CONFIG += console c++11
CONFIG -= app_bundle
CONFIG -= qt

# The following define makes your compiler emit warnings if you use
# any feature of Qt which has been marked as deprecated (the exact warnings
# depend on your compiler). Please consult the documentation of the
# deprecated API in order to know how to port your code away from it.
DEFINES += QT_DEPRECATED_WARNINGS

# You can also make your code fail to compile if you use deprecated APIs.
# In order to do so, uncomment the following line.
# You can also select to disable deprecated APIs only up to a certain version of Qt.
#DEFINES += QT_DISABLE_DEPRECATED_BEFORE=0x060000    # disables all the APIs deprecated before Qt 6.0.0


SOURCES += \
        main.cpp \
    base/vector3.cpp \
    base/lodepng.cpp \
    base/scene.cpp \
    base/shape/sphere.cpp \
    base/shape/object.cpp \
    base/ray.cpp \
    base/shape/lightsphere.cpp \
    base/camera.cpp \
    base/infras.cpp

HEADERS += \
    base/vector3.h \
    base/include.h \
    base/point.h \
    base/lodepng.h \
    base/color.h \
    base/scene.h \
    base/object.h \
    base/shape/object.h \
    base/shape/sphere.h \
    base/infras.h \
    base/ray.h \
    base/shape/lightsphere.h \
    base/camera.h \
    base/Eigen/Cholesky/LDLT.h \
    base/Eigen/Cholesky/LLT.h \
    base/Eigen/Cholesky/LLT_LAPACKE.h \
    base/Eigen/CholmodSupport/CholmodSupport.h \
    base/Eigen/Core/arch/AltiVec/Complex.h \
    base/Eigen/Core/arch/AltiVec/MathFunctions.h \
    base/Eigen/Core/arch/AltiVec/PacketMath.h \
    base/Eigen/Core/arch/AVX/Complex.h \
    base/Eigen/Core/arch/AVX/MathFunctions.h \
    base/Eigen/Core/arch/AVX/PacketMath.h \
    base/Eigen/Core/arch/AVX/TypeCasting.h \
    base/Eigen/Core/arch/AVX512/MathFunctions.h \
    base/Eigen/Core/arch/AVX512/PacketMath.h \
    base/Eigen/Core/arch/CUDA/Complex.h \
    base/Eigen/Core/arch/CUDA/Half.h \
    base/Eigen/Core/arch/CUDA/MathFunctions.h \
    base/Eigen/Core/arch/CUDA/PacketMath.h \
    base/Eigen/Core/arch/CUDA/PacketMathHalf.h \
    base/Eigen/Core/arch/CUDA/TypeCasting.h \
    base/Eigen/Core/arch/Default/ConjHelper.h \
    base/Eigen/Core/arch/Default/Settings.h \
    base/Eigen/Core/arch/NEON/Complex.h \
    base/Eigen/Core/arch/NEON/MathFunctions.h \
    base/Eigen/Core/arch/NEON/PacketMath.h \
    base/Eigen/Core/arch/SSE/Complex.h \
    base/Eigen/Core/arch/SSE/MathFunctions.h \
    base/Eigen/Core/arch/SSE/PacketMath.h \
    base/Eigen/Core/arch/SSE/TypeCasting.h \
    base/Eigen/Core/arch/ZVector/Complex.h \
    base/Eigen/Core/arch/ZVector/MathFunctions.h \
    base/Eigen/Core/arch/ZVector/PacketMath.h \
    base/Eigen/Core/functors/AssignmentFunctors.h \
    base/Eigen/Core/functors/BinaryFunctors.h \
    base/Eigen/Core/functors/NullaryFunctors.h \
    base/Eigen/Core/functors/StlFunctors.h \
    base/Eigen/Core/functors/TernaryFunctors.h \
    base/Eigen/Core/functors/UnaryFunctors.h \
    base/Eigen/Core/products/GeneralBlockPanelKernel.h \
    base/Eigen/Core/products/GeneralMatrixMatrix.h \
    base/Eigen/Core/products/GeneralMatrixMatrix_BLAS.h \
    base/Eigen/Core/products/GeneralMatrixMatrixTriangular.h \
    base/Eigen/Core/products/GeneralMatrixMatrixTriangular_BLAS.h \
    base/Eigen/Core/products/GeneralMatrixVector.h \
    base/Eigen/Core/products/GeneralMatrixVector_BLAS.h \
    base/Eigen/Core/products/Parallelizer.h \
    base/Eigen/Core/products/SelfadjointMatrixMatrix.h \
    base/Eigen/Core/products/SelfadjointMatrixMatrix_BLAS.h \
    base/Eigen/Core/products/SelfadjointMatrixVector.h \
    base/Eigen/Core/products/SelfadjointMatrixVector_BLAS.h \
    base/Eigen/Core/products/SelfadjointProduct.h \
    base/Eigen/Core/products/SelfadjointRank2Update.h \
    base/Eigen/Core/products/TriangularMatrixMatrix.h \
    base/Eigen/Core/products/TriangularMatrixMatrix_BLAS.h \
    base/Eigen/Core/products/TriangularMatrixVector.h \
    base/Eigen/Core/products/TriangularMatrixVector_BLAS.h \
    base/Eigen/Core/products/TriangularSolverMatrix.h \
    base/Eigen/Core/products/TriangularSolverMatrix_BLAS.h \
    base/Eigen/Core/products/TriangularSolverVector.h \
    base/Eigen/Core/util/BlasUtil.h \
    base/Eigen/Core/util/Constants.h \
    base/Eigen/Core/util/DisableStupidWarnings.h \
    base/Eigen/Core/util/ForwardDeclarations.h \
    base/Eigen/Core/util/Macros.h \
    base/Eigen/Core/util/Memory.h \
    base/Eigen/Core/util/Meta.h \
    base/Eigen/Core/util/MKL_support.h \
    base/Eigen/Core/util/NonMPL2.h \
    base/Eigen/Core/util/ReenableStupidWarnings.h \
    base/Eigen/Core/util/StaticAssert.h \
    base/Eigen/Core/util/XprHelper.h \
    base/Eigen/Core/Array.h \
    base/Eigen/Core/ArrayBase.h \
    base/Eigen/Core/ArrayWrapper.h \
    base/Eigen/Core/Assign.h \
    base/Eigen/Core/Assign_MKL.h \
    base/Eigen/Core/AssignEvaluator.h \
    base/Eigen/Core/BandMatrix.h \
    base/Eigen/Core/Block.h \
    base/Eigen/Core/BooleanRedux.h \
    base/Eigen/Core/CommaInitializer.h \
    base/Eigen/Core/ConditionEstimator.h \
    base/Eigen/Core/CoreEvaluators.h \
    base/Eigen/Core/CoreIterators.h \
    base/Eigen/Core/CwiseBinaryOp.h \
    base/Eigen/Core/CwiseNullaryOp.h \
    base/Eigen/Core/CwiseTernaryOp.h \
    base/Eigen/Core/CwiseUnaryOp.h \
    base/Eigen/Core/CwiseUnaryView.h \
    base/Eigen/Core/DenseBase.h \
    base/Eigen/Core/DenseCoeffsBase.h \
    base/Eigen/Core/DenseStorage.h \
    base/Eigen/Core/Diagonal.h \
    base/Eigen/Core/DiagonalMatrix.h \
    base/Eigen/Core/DiagonalProduct.h \
    base/Eigen/Core/Dot.h \
    base/Eigen/Core/EigenBase.h \
    base/Eigen/Core/ForceAlignedAccess.h \
    base/Eigen/Core/Fuzzy.h \
    base/Eigen/Core/GeneralProduct.h \
    base/Eigen/Core/GenericPacketMath.h \
    base/Eigen/Core/GlobalFunctions.h \
    base/Eigen/Core/Inverse.h \
    base/Eigen/Core/IO.h \
    base/Eigen/Core/Map.h \
    base/Eigen/Core/MapBase.h \
    base/Eigen/Core/MathFunctions.h \
    base/Eigen/Core/MathFunctionsImpl.h \
    base/Eigen/Core/Matrix.h \
    base/Eigen/Core/MatrixBase.h \
    base/Eigen/Core/NestByValue.h \
    base/Eigen/Core/NoAlias.h \
    base/Eigen/Core/NumTraits.h \
    base/Eigen/Core/PermutationMatrix.h \
    base/Eigen/Core/PlainObjectBase.h \
    base/Eigen/Core/Product.h \
    base/Eigen/Core/ProductEvaluators.h \
    base/Eigen/Core/Random.h \
    base/Eigen/Core/Redux.h \
    base/Eigen/Core/Ref.h \
    base/Eigen/Core/Replicate.h \
    base/Eigen/Core/ReturnByValue.h \
    base/Eigen/Core/Reverse.h \
    base/Eigen/Core/Select.h \
    base/Eigen/Core/SelfAdjointView.h \
    base/Eigen/Core/SelfCwiseBinaryOp.h \
    base/Eigen/Core/Solve.h \
    base/Eigen/Core/SolverBase.h \
    base/Eigen/Core/SolveTriangular.h \
    base/Eigen/Core/StableNorm.h \
    base/Eigen/Core/Stride.h \
    base/Eigen/Core/Swap.h \
    base/Eigen/Core/Transpose.h \
    base/Eigen/Core/Transpositions.h \
    base/Eigen/Core/TriangularMatrix.h \
    base/Eigen/Core/VectorBlock.h \
    base/Eigen/Core/VectorwiseOp.h \
    base/Eigen/Core/Visitor.h \
    base/Eigen/Eigenvalues/ComplexEigenSolver.h \
    base/Eigen/Eigenvalues/ComplexSchur.h \
    base/Eigen/Eigenvalues/ComplexSchur_LAPACKE.h \
    base/Eigen/Eigenvalues/EigenSolver.h \
    base/Eigen/Eigenvalues/GeneralizedEigenSolver.h \
    base/Eigen/Eigenvalues/GeneralizedSelfAdjointEigenSolver.h \
    base/Eigen/Eigenvalues/HessenbergDecomposition.h \
    base/Eigen/Eigenvalues/MatrixBaseEigenvalues.h \
    base/Eigen/Eigenvalues/RealQZ.h \
    base/Eigen/Eigenvalues/RealSchur.h \
    base/Eigen/Eigenvalues/RealSchur_LAPACKE.h \
    base/Eigen/Eigenvalues/SelfAdjointEigenSolver.h \
    base/Eigen/Eigenvalues/SelfAdjointEigenSolver_LAPACKE.h \
    base/Eigen/Eigenvalues/Tridiagonalization.h \
    base/Eigen/Geometry/arch/Geometry_SSE.h \
    base/Eigen/Geometry/AlignedBox.h \
    base/Eigen/Geometry/AngleAxis.h \
    base/Eigen/Geometry/EulerAngles.h \
    base/Eigen/Geometry/Homogeneous.h \
    base/Eigen/Geometry/Hyperplane.h \
    base/Eigen/Geometry/OrthoMethods.h \
    base/Eigen/Geometry/ParametrizedLine.h \
    base/Eigen/Geometry/Quaternion.h \
    base/Eigen/Geometry/Rotation2D.h \
    base/Eigen/Geometry/RotationBase.h \
    base/Eigen/Geometry/Scaling.h \
    base/Eigen/Geometry/Transform.h \
    base/Eigen/Geometry/Translation.h \
    base/Eigen/Geometry/Umeyama.h \
    base/Eigen/Householder/BlockHouseholder.h \
    base/Eigen/Householder/Householder.h \
    base/Eigen/Householder/HouseholderSequence.h \
    base/Eigen/IterativeLinearSolvers/BasicPreconditioners.h \
    base/Eigen/IterativeLinearSolvers/BiCGSTAB.h \
    base/Eigen/IterativeLinearSolvers/ConjugateGradient.h \
    base/Eigen/IterativeLinearSolvers/IncompleteCholesky.h \
    base/Eigen/IterativeLinearSolvers/IncompleteLUT.h \
    base/Eigen/IterativeLinearSolvers/IterativeSolverBase.h \
    base/Eigen/IterativeLinearSolvers/LeastSquareConjugateGradient.h \
    base/Eigen/IterativeLinearSolvers/SolveWithGuess.h \
    base/Eigen/Jacobi/Jacobi.h \
    base/Eigen/LU/arch/Inverse_SSE.h \
    base/Eigen/LU/Determinant.h \
    base/Eigen/LU/FullPivLU.h \
    base/Eigen/LU/InverseImpl.h \
    base/Eigen/LU/PartialPivLU.h \
    base/Eigen/LU/PartialPivLU_LAPACKE.h \
    base/Eigen/MetisSupport/MetisSupport.h \
    base/Eigen/misc/blas.h \
    base/Eigen/misc/Image.h \
    base/Eigen/misc/Kernel.h \
    base/Eigen/misc/lapack.h \
    base/Eigen/misc/lapacke.h \
    base/Eigen/misc/lapacke_mangling.h \
    base/Eigen/misc/RealSvd2x2.h \
    base/Eigen/OrderingMethods/Amd.h \
    base/Eigen/OrderingMethods/Eigen_Colamd.h \
    base/Eigen/OrderingMethods/Ordering.h \
    base/Eigen/PardisoSupport/PardisoSupport.h \
    base/Eigen/PaStiXSupport/PaStiXSupport.h \
    base/Eigen/plugins/ArrayCwiseBinaryOps.h \
    base/Eigen/plugins/ArrayCwiseUnaryOps.h \
    base/Eigen/plugins/BlockMethods.h \
    base/Eigen/plugins/CommonCwiseBinaryOps.h \
    base/Eigen/plugins/CommonCwiseUnaryOps.h \
    base/Eigen/plugins/MatrixCwiseBinaryOps.h \
    base/Eigen/plugins/MatrixCwiseUnaryOps.h \
    base/Eigen/QR/ColPivHouseholderQR.h \
    base/Eigen/QR/ColPivHouseholderQR_LAPACKE.h \
    base/Eigen/QR/CompleteOrthogonalDecomposition.h \
    base/Eigen/QR/FullPivHouseholderQR.h \
    base/Eigen/QR/HouseholderQR.h \
    base/Eigen/QR/HouseholderQR_LAPACKE.h \
    base/Eigen/SparseCholesky/SimplicialCholesky.h \
    base/Eigen/SparseCholesky/SimplicialCholesky_impl.h \
    base/Eigen/SparseCore/AmbiVector.h \
    base/Eigen/SparseCore/CompressedStorage.h \
    base/Eigen/SparseCore/ConservativeSparseSparseProduct.h \
    base/Eigen/SparseCore/MappedSparseMatrix.h \
    base/Eigen/SparseCore/SparseAssign.h \
    base/Eigen/SparseCore/SparseBlock.h \
    base/Eigen/SparseCore/SparseColEtree.h \
    base/Eigen/SparseCore/SparseCompressedBase.h \
    base/Eigen/SparseCore/SparseCwiseBinaryOp.h \
    base/Eigen/SparseCore/SparseCwiseUnaryOp.h \
    base/Eigen/SparseCore/SparseDenseProduct.h \
    base/Eigen/SparseCore/SparseDiagonalProduct.h \
    base/Eigen/SparseCore/SparseDot.h \
    base/Eigen/SparseCore/SparseFuzzy.h \
    base/Eigen/SparseCore/SparseMap.h \
    base/Eigen/SparseCore/SparseMatrix.h \
    base/Eigen/SparseCore/SparseMatrixBase.h \
    base/Eigen/SparseCore/SparsePermutation.h \
    base/Eigen/SparseCore/SparseProduct.h \
    base/Eigen/SparseCore/SparseRedux.h \
    base/Eigen/SparseCore/SparseRef.h \
    base/Eigen/SparseCore/SparseSelfAdjointView.h \
    base/Eigen/SparseCore/SparseSolverBase.h \
    base/Eigen/SparseCore/SparseSparseProductWithPruning.h \
    base/Eigen/SparseCore/SparseTranspose.h \
    base/Eigen/SparseCore/SparseTriangularView.h \
    base/Eigen/SparseCore/SparseUtil.h \
    base/Eigen/SparseCore/SparseVector.h \
    base/Eigen/SparseCore/SparseView.h \
    base/Eigen/SparseCore/TriangularSolver.h \
    base/Eigen/SparseLU/SparseLU.h \
    base/Eigen/SparseLU/SparseLU_column_bmod.h \
    base/Eigen/SparseLU/SparseLU_column_dfs.h \
    base/Eigen/SparseLU/SparseLU_copy_to_ucol.h \
    base/Eigen/SparseLU/SparseLU_gemm_kernel.h \
    base/Eigen/SparseLU/SparseLU_heap_relax_snode.h \
    base/Eigen/SparseLU/SparseLU_kernel_bmod.h \
    base/Eigen/SparseLU/SparseLU_Memory.h \
    base/Eigen/SparseLU/SparseLU_panel_bmod.h \
    base/Eigen/SparseLU/SparseLU_panel_dfs.h \
    base/Eigen/SparseLU/SparseLU_pivotL.h \
    base/Eigen/SparseLU/SparseLU_pruneL.h \
    base/Eigen/SparseLU/SparseLU_relax_snode.h \
    base/Eigen/SparseLU/SparseLU_Structs.h \
    base/Eigen/SparseLU/SparseLU_SupernodalMatrix.h \
    base/Eigen/SparseLU/SparseLU_Utils.h \
    base/Eigen/SparseLU/SparseLUImpl.h \
    base/Eigen/SparseQR/SparseQR.h \
    base/Eigen/SPQRSupport/SuiteSparseQRSupport.h \
    base/Eigen/StlSupport/details.h \
    base/Eigen/StlSupport/StdDeque.h \
    base/Eigen/StlSupport/StdList.h \
    base/Eigen/StlSupport/StdVector.h \
    base/Eigen/SuperLUSupport/SuperLUSupport.h \
    base/Eigen/SVD/BDCSVD.h \
    base/Eigen/SVD/JacobiSVD.h \
    base/Eigen/SVD/JacobiSVD_LAPACKE.h \
    base/Eigen/SVD/SVDBase.h \
    base/Eigen/SVD/UpperBidiagonalization.h \
    base/Eigen/UmfPackSupport/UmfPackSupport.h \
    base/Eigen/Dense \
    base/Eigen/Cholesky.h \
    base/Eigen/CholmodSupport.h \
    base/Eigen/Core.h \
    base/Eigen/Dense.h \
    base/Eigen/Eigen.h \
    base/Eigen/Eigenvalues.h \
    base/Eigen/Geometry.h \
    base/Eigen/Householder.h \
    base/Eigen/IterativeLinearSolvers.h \
    base/Eigen/Jacobi.h \
    base/Eigen/LU.h \
    base/Eigen/MetisSupport.h \
    base/Eigen/OrderingMethods.h \
    base/Eigen/PardisoSupport.h \
    base/Eigen/PaStiXSupport.h \
    base/Eigen/QR.h \
    base/Eigen/QtAlignedMalloc.h \
    base/Eigen/Sparse.h \
    base/Eigen/SparseCholesky.h \
    base/Eigen/SparseCore.h \
    base/Eigen/SparseLU.h \
    base/Eigen/SparseQR.h \
    base/Eigen/SPQRSupport.h \
    base/Eigen/StdDeque.h \
    base/Eigen/StdList.h \
    base/Eigen/StdVector.h \
    base/Eigen/SuperLUSupport.h \
    base/Eigen/SVD.h \
    base/Eigen/UmfPackSupport.h \
    base/Eigen/src/Cholesky/LDLT.h \
    base/Eigen/src/Cholesky/LLT.h \
    base/Eigen/src/Cholesky/LLT_LAPACKE.h \
    base/Eigen/src/CholmodSupport/CholmodSupport.h \
    base/Eigen/src/Core/arch/AltiVec/Complex.h \
    base/Eigen/src/Core/arch/AltiVec/MathFunctions.h \
    base/Eigen/src/Core/arch/AltiVec/PacketMath.h \
    base/Eigen/src/Core/arch/AVX/Complex.h \
    base/Eigen/src/Core/arch/AVX/MathFunctions.h \
    base/Eigen/src/Core/arch/AVX/PacketMath.h \
    base/Eigen/src/Core/arch/AVX/TypeCasting.h \
    base/Eigen/src/Core/arch/AVX512/MathFunctions.h \
    base/Eigen/src/Core/arch/AVX512/PacketMath.h \
    base/Eigen/src/Core/arch/CUDA/Complex.h \
    base/Eigen/src/Core/arch/CUDA/Half.h \
    base/Eigen/src/Core/arch/CUDA/MathFunctions.h \
    base/Eigen/src/Core/arch/CUDA/PacketMath.h \
    base/Eigen/src/Core/arch/CUDA/PacketMathHalf.h \
    base/Eigen/src/Core/arch/CUDA/TypeCasting.h \
    base/Eigen/src/Core/arch/Default/ConjHelper.h \
    base/Eigen/src/Core/arch/Default/Settings.h \
    base/Eigen/src/Core/arch/NEON/Complex.h \
    base/Eigen/src/Core/arch/NEON/MathFunctions.h \
    base/Eigen/src/Core/arch/NEON/PacketMath.h \
    base/Eigen/src/Core/arch/SSE/Complex.h \
    base/Eigen/src/Core/arch/SSE/MathFunctions.h \
    base/Eigen/src/Core/arch/SSE/PacketMath.h \
    base/Eigen/src/Core/arch/SSE/TypeCasting.h \
    base/Eigen/src/Core/arch/ZVector/Complex.h \
    base/Eigen/src/Core/arch/ZVector/MathFunctions.h \
    base/Eigen/src/Core/arch/ZVector/PacketMath.h \
    base/Eigen/src/Core/functors/AssignmentFunctors.h \
    base/Eigen/src/Core/functors/BinaryFunctors.h \
    base/Eigen/src/Core/functors/NullaryFunctors.h \
    base/Eigen/src/Core/functors/StlFunctors.h \
    base/Eigen/src/Core/functors/TernaryFunctors.h \
    base/Eigen/src/Core/functors/UnaryFunctors.h \
    base/Eigen/src/Core/products/GeneralBlockPanelKernel.h \
    base/Eigen/src/Core/products/GeneralMatrixMatrix.h \
    base/Eigen/src/Core/products/GeneralMatrixMatrix_BLAS.h \
    base/Eigen/src/Core/products/GeneralMatrixMatrixTriangular.h \
    base/Eigen/src/Core/products/GeneralMatrixMatrixTriangular_BLAS.h \
    base/Eigen/src/Core/products/GeneralMatrixVector.h \
    base/Eigen/src/Core/products/GeneralMatrixVector_BLAS.h \
    base/Eigen/src/Core/products/Parallelizer.h \
    base/Eigen/src/Core/products/SelfadjointMatrixMatrix.h \
    base/Eigen/src/Core/products/SelfadjointMatrixMatrix_BLAS.h \
    base/Eigen/src/Core/products/SelfadjointMatrixVector.h \
    base/Eigen/src/Core/products/SelfadjointMatrixVector_BLAS.h \
    base/Eigen/src/Core/products/SelfadjointProduct.h \
    base/Eigen/src/Core/products/SelfadjointRank2Update.h \
    base/Eigen/src/Core/products/TriangularMatrixMatrix.h \
    base/Eigen/src/Core/products/TriangularMatrixMatrix_BLAS.h \
    base/Eigen/src/Core/products/TriangularMatrixVector.h \
    base/Eigen/src/Core/products/TriangularMatrixVector_BLAS.h \
    base/Eigen/src/Core/products/TriangularSolverMatrix.h \
    base/Eigen/src/Core/products/TriangularSolverMatrix_BLAS.h \
    base/Eigen/src/Core/products/TriangularSolverVector.h \
    base/Eigen/src/Core/util/BlasUtil.h \
    base/Eigen/src/Core/util/Constants.h \
    base/Eigen/src/Core/util/DisableStupidWarnings.h \
    base/Eigen/src/Core/util/ForwardDeclarations.h \
    base/Eigen/src/Core/util/Macros.h \
    base/Eigen/src/Core/util/Memory.h \
    base/Eigen/src/Core/util/Meta.h \
    base/Eigen/src/Core/util/MKL_support.h \
    base/Eigen/src/Core/util/NonMPL2.h \
    base/Eigen/src/Core/util/ReenableStupidWarnings.h \
    base/Eigen/src/Core/util/StaticAssert.h \
    base/Eigen/src/Core/util/XprHelper.h \
    base/Eigen/src/Core/Array.h \
    base/Eigen/src/Core/ArrayBase.h \
    base/Eigen/src/Core/ArrayWrapper.h \
    base/Eigen/src/Core/Assign.h \
    base/Eigen/src/Core/Assign_MKL.h \
    base/Eigen/src/Core/AssignEvaluator.h \
    base/Eigen/src/Core/BandMatrix.h \
    base/Eigen/src/Core/Block.h \
    base/Eigen/src/Core/BooleanRedux.h \
    base/Eigen/src/Core/CommaInitializer.h \
    base/Eigen/src/Core/ConditionEstimator.h \
    base/Eigen/src/Core/CoreEvaluators.h \
    base/Eigen/src/Core/CoreIterators.h \
    base/Eigen/src/Core/CwiseBinaryOp.h \
    base/Eigen/src/Core/CwiseNullaryOp.h \
    base/Eigen/src/Core/CwiseTernaryOp.h \
    base/Eigen/src/Core/CwiseUnaryOp.h \
    base/Eigen/src/Core/CwiseUnaryView.h \
    base/Eigen/src/Core/DenseBase.h \
    base/Eigen/src/Core/DenseCoeffsBase.h \
    base/Eigen/src/Core/DenseStorage.h \
    base/Eigen/src/Core/Diagonal.h \
    base/Eigen/src/Core/DiagonalMatrix.h \
    base/Eigen/src/Core/DiagonalProduct.h \
    base/Eigen/src/Core/Dot.h \
    base/Eigen/src/Core/EigenBase.h \
    base/Eigen/src/Core/ForceAlignedAccess.h \
    base/Eigen/src/Core/Fuzzy.h \
    base/Eigen/src/Core/GeneralProduct.h \
    base/Eigen/src/Core/GenericPacketMath.h \
    base/Eigen/src/Core/GlobalFunctions.h \
    base/Eigen/src/Core/Inverse.h \
    base/Eigen/src/Core/IO.h \
    base/Eigen/src/Core/Map.h \
    base/Eigen/src/Core/MapBase.h \
    base/Eigen/src/Core/MathFunctions.h \
    base/Eigen/src/Core/MathFunctionsImpl.h \
    base/Eigen/src/Core/Matrix.h \
    base/Eigen/src/Core/MatrixBase.h \
    base/Eigen/src/Core/NestByValue.h \
    base/Eigen/src/Core/NoAlias.h \
    base/Eigen/src/Core/NumTraits.h \
    base/Eigen/src/Core/PermutationMatrix.h \
    base/Eigen/src/Core/PlainObjectBase.h \
    base/Eigen/src/Core/Product.h \
    base/Eigen/src/Core/ProductEvaluators.h \
    base/Eigen/src/Core/Random.h \
    base/Eigen/src/Core/Redux.h \
    base/Eigen/src/Core/Ref.h \
    base/Eigen/src/Core/Replicate.h \
    base/Eigen/src/Core/ReturnByValue.h \
    base/Eigen/src/Core/Reverse.h \
    base/Eigen/src/Core/Select.h \
    base/Eigen/src/Core/SelfAdjointView.h \
    base/Eigen/src/Core/SelfCwiseBinaryOp.h \
    base/Eigen/src/Core/Solve.h \
    base/Eigen/src/Core/SolverBase.h \
    base/Eigen/src/Core/SolveTriangular.h \
    base/Eigen/src/Core/StableNorm.h \
    base/Eigen/src/Core/Stride.h \
    base/Eigen/src/Core/Swap.h \
    base/Eigen/src/Core/Transpose.h \
    base/Eigen/src/Core/Transpositions.h \
    base/Eigen/src/Core/TriangularMatrix.h \
    base/Eigen/src/Core/VectorBlock.h \
    base/Eigen/src/Core/VectorwiseOp.h \
    base/Eigen/src/Core/Visitor.h \
    base/Eigen/src/Eigenvalues/ComplexEigenSolver.h \
    base/Eigen/src/Eigenvalues/ComplexSchur.h \
    base/Eigen/src/Eigenvalues/ComplexSchur_LAPACKE.h \
    base/Eigen/src/Eigenvalues/EigenSolver.h \
    base/Eigen/src/Eigenvalues/GeneralizedEigenSolver.h \
    base/Eigen/src/Eigenvalues/GeneralizedSelfAdjointEigenSolver.h \
    base/Eigen/src/Eigenvalues/HessenbergDecomposition.h \
    base/Eigen/src/Eigenvalues/MatrixBaseEigenvalues.h \
    base/Eigen/src/Eigenvalues/RealQZ.h \
    base/Eigen/src/Eigenvalues/RealSchur.h \
    base/Eigen/src/Eigenvalues/RealSchur_LAPACKE.h \
    base/Eigen/src/Eigenvalues/SelfAdjointEigenSolver.h \
    base/Eigen/src/Eigenvalues/SelfAdjointEigenSolver_LAPACKE.h \
    base/Eigen/src/Eigenvalues/Tridiagonalization.h \
    base/Eigen/src/Geometry/arch/Geometry_SSE.h \
    base/Eigen/src/Geometry/AlignedBox.h \
    base/Eigen/src/Geometry/AngleAxis.h \
    base/Eigen/src/Geometry/EulerAngles.h \
    base/Eigen/src/Geometry/Homogeneous.h \
    base/Eigen/src/Geometry/Hyperplane.h \
    base/Eigen/src/Geometry/OrthoMethods.h \
    base/Eigen/src/Geometry/ParametrizedLine.h \
    base/Eigen/src/Geometry/Quaternion.h \
    base/Eigen/src/Geometry/Rotation2D.h \
    base/Eigen/src/Geometry/RotationBase.h \
    base/Eigen/src/Geometry/Scaling.h \
    base/Eigen/src/Geometry/Transform.h \
    base/Eigen/src/Geometry/Translation.h \
    base/Eigen/src/Geometry/Umeyama.h \
    base/Eigen/src/Householder/BlockHouseholder.h \
    base/Eigen/src/Householder/Householder.h \
    base/Eigen/src/Householder/HouseholderSequence.h \
    base/Eigen/src/IterativeLinearSolvers/BasicPreconditioners.h \
    base/Eigen/src/IterativeLinearSolvers/BiCGSTAB.h \
    base/Eigen/src/IterativeLinearSolvers/ConjugateGradient.h \
    base/Eigen/src/IterativeLinearSolvers/IncompleteCholesky.h \
    base/Eigen/src/IterativeLinearSolvers/IncompleteLUT.h \
    base/Eigen/src/IterativeLinearSolvers/IterativeSolverBase.h \
    base/Eigen/src/IterativeLinearSolvers/LeastSquareConjugateGradient.h \
    base/Eigen/src/IterativeLinearSolvers/SolveWithGuess.h \
    base/Eigen/src/Jacobi/Jacobi.h \
    base/Eigen/src/LU/arch/Inverse_SSE.h \
    base/Eigen/src/LU/Determinant.h \
    base/Eigen/src/LU/FullPivLU.h \
    base/Eigen/src/LU/InverseImpl.h \
    base/Eigen/src/LU/PartialPivLU.h \
    base/Eigen/src/LU/PartialPivLU_LAPACKE.h \
    base/Eigen/src/MetisSupport/MetisSupport.h \
    base/Eigen/src/misc/blas.h \
    base/Eigen/src/misc/Image.h \
    base/Eigen/src/misc/Kernel.h \
    base/Eigen/src/misc/lapack.h \
    base/Eigen/src/misc/lapacke.h \
    base/Eigen/src/misc/lapacke_mangling.h \
    base/Eigen/src/misc/RealSvd2x2.h \
    base/Eigen/src/OrderingMethods/Amd.h \
    base/Eigen/src/OrderingMethods/Eigen_Colamd.h \
    base/Eigen/src/OrderingMethods/Ordering.h \
    base/Eigen/src/PardisoSupport/PardisoSupport.h \
    base/Eigen/src/PaStiXSupport/PaStiXSupport.h \
    base/Eigen/src/plugins/ArrayCwiseBinaryOps.h \
    base/Eigen/src/plugins/ArrayCwiseUnaryOps.h \
    base/Eigen/src/plugins/BlockMethods.h \
    base/Eigen/src/plugins/CommonCwiseBinaryOps.h \
    base/Eigen/src/plugins/CommonCwiseUnaryOps.h \
    base/Eigen/src/plugins/MatrixCwiseBinaryOps.h \
    base/Eigen/src/plugins/MatrixCwiseUnaryOps.h \
    base/Eigen/src/QR/ColPivHouseholderQR.h \
    base/Eigen/src/QR/ColPivHouseholderQR_LAPACKE.h \
    base/Eigen/src/QR/CompleteOrthogonalDecomposition.h \
    base/Eigen/src/QR/FullPivHouseholderQR.h \
    base/Eigen/src/QR/HouseholderQR.h \
    base/Eigen/src/QR/HouseholderQR_LAPACKE.h \
    base/Eigen/src/SparseCholesky/SimplicialCholesky.h \
    base/Eigen/src/SparseCholesky/SimplicialCholesky_impl.h \
    base/Eigen/src/SparseCore/AmbiVector.h \
    base/Eigen/src/SparseCore/CompressedStorage.h \
    base/Eigen/src/SparseCore/ConservativeSparseSparseProduct.h \
    base/Eigen/src/SparseCore/MappedSparseMatrix.h \
    base/Eigen/src/SparseCore/SparseAssign.h \
    base/Eigen/src/SparseCore/SparseBlock.h \
    base/Eigen/src/SparseCore/SparseColEtree.h \
    base/Eigen/src/SparseCore/SparseCompressedBase.h \
    base/Eigen/src/SparseCore/SparseCwiseBinaryOp.h \
    base/Eigen/src/SparseCore/SparseCwiseUnaryOp.h \
    base/Eigen/src/SparseCore/SparseDenseProduct.h \
    base/Eigen/src/SparseCore/SparseDiagonalProduct.h \
    base/Eigen/src/SparseCore/SparseDot.h \
    base/Eigen/src/SparseCore/SparseFuzzy.h \
    base/Eigen/src/SparseCore/SparseMap.h \
    base/Eigen/src/SparseCore/SparseMatrix.h \
    base/Eigen/src/SparseCore/SparseMatrixBase.h \
    base/Eigen/src/SparseCore/SparsePermutation.h \
    base/Eigen/src/SparseCore/SparseProduct.h \
    base/Eigen/src/SparseCore/SparseRedux.h \
    base/Eigen/src/SparseCore/SparseRef.h \
    base/Eigen/src/SparseCore/SparseSelfAdjointView.h \
    base/Eigen/src/SparseCore/SparseSolverBase.h \
    base/Eigen/src/SparseCore/SparseSparseProductWithPruning.h \
    base/Eigen/src/SparseCore/SparseTranspose.h \
    base/Eigen/src/SparseCore/SparseTriangularView.h \
    base/Eigen/src/SparseCore/SparseUtil.h \
    base/Eigen/src/SparseCore/SparseVector.h \
    base/Eigen/src/SparseCore/SparseView.h \
    base/Eigen/src/SparseCore/TriangularSolver.h \
    base/Eigen/src/SparseLU/SparseLU.h \
    base/Eigen/src/SparseLU/SparseLU_column_bmod.h \
    base/Eigen/src/SparseLU/SparseLU_column_dfs.h \
    base/Eigen/src/SparseLU/SparseLU_copy_to_ucol.h \
    base/Eigen/src/SparseLU/SparseLU_gemm_kernel.h \
    base/Eigen/src/SparseLU/SparseLU_heap_relax_snode.h \
    base/Eigen/src/SparseLU/SparseLU_kernel_bmod.h \
    base/Eigen/src/SparseLU/SparseLU_Memory.h \
    base/Eigen/src/SparseLU/SparseLU_panel_bmod.h \
    base/Eigen/src/SparseLU/SparseLU_panel_dfs.h \
    base/Eigen/src/SparseLU/SparseLU_pivotL.h \
    base/Eigen/src/SparseLU/SparseLU_pruneL.h \
    base/Eigen/src/SparseLU/SparseLU_relax_snode.h \
    base/Eigen/src/SparseLU/SparseLU_Structs.h \
    base/Eigen/src/SparseLU/SparseLU_SupernodalMatrix.h \
    base/Eigen/src/SparseLU/SparseLU_Utils.h \
    base/Eigen/src/SparseLU/SparseLUImpl.h \
    base/Eigen/src/SparseQR/SparseQR.h \
    base/Eigen/src/SPQRSupport/SuiteSparseQRSupport.h \
    base/Eigen/src/StlSupport/details.h \
    base/Eigen/src/StlSupport/StdDeque.h \
    base/Eigen/src/StlSupport/StdList.h \
    base/Eigen/src/StlSupport/StdVector.h \
    base/Eigen/src/SuperLUSupport/SuperLUSupport.h \
    base/Eigen/src/SVD/BDCSVD.h \
    base/Eigen/src/SVD/JacobiSVD.h \
    base/Eigen/src/SVD/JacobiSVD_LAPACKE.h \
    base/Eigen/src/SVD/SVDBase.h \
    base/Eigen/src/SVD/UpperBidiagonalization.h \
    base/Eigen/src/UmfPackSupport/UmfPackSupport.h

FORMS +=

DISTFILES +=
